version: "3.3"

services:
  db:
    image: "mongo"
    container_name: "mongodb"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
    ports:
      - "27017-27019:27017-27019"

  crawler:
    build: .
